title: "Karthik Nandakumar"
baseurl: "" # keep empty if deployed at root
permalink: pretty

# Clean URL mapping for each page
defaults:
  - scope:
      path: "index.html"
    values:
      permalink: /
      title: "Karthik Nandakumar - Portfolio"

  - scope:
      path: "projects.html"
    values:
      permalink: /projects/
      title: "Karthik Nandakumar - Projects"

  - scope:
      path: "experiences.html"
    values:
      permalink: /experiences/
      title: "Experiences"

  - scope:
      path: "certifications.html"
    values:
      permalink: /certifications/
      title: "Certifications"